### ISSUE TITLE
Correct cert shows as "superseded"

### ISSUE THREAD

**Issue by dlapiduz** [SSLMate/sslmate#12]
In the process of purchasing a cert I picked the wrong email for confirmation so I cancelled it and started again.
When I finished downloading the new cert I went to the dashboard to check on it and it shows as "superseded" by the original one.

There might be some timing issue since the "correct" cert shows up as the old one.

**Comment by AGWA** [comment]
Hi @dlapiduz, thanks for reporting this.  I've fixed this for your account.  We'll soon be improving the behavior for placing a new order when there's already a pending order with the same name.
