### ISSUE TITLE
Reissued/Revoked cert

### ISSUE THREAD

**Issue by vzvenyach** [SSLMate/sslmate#13]
Hello,
Recently I ran `sslmate buy *.dccode.gov` and had to Ctrl+C out because I needed confirmation. Later, not realizing that the private.key was in my home directory and was created by sslmate (thinking it was a remnant self-signed key/cert), i deleted it. Later, once domain confirmation was complete, I ran `sslmate download *.dccode.gov`. All well, except no private key in `etc/sslmate` (and because I deleted it from home). So, I ran `sslmate reissue *.dccode.gov` but got this error: 
```
Generating private key... Done.
Generating CSR... Done.
Reissuing cert...
Error: Reissuing your certificate failed - please email support@sslmate.com
```
Well... thinking that I needed to revoke the existing cert, I ran `sslmate revoke -a *.dccode.gov` and tried to run `sslmate reissue *.dccode.gov` again. But then I got this error: 
```
Generating private key... Done.
Generating CSR... Done.
Reissuing cert...
Error: You do not currently have a certificate in your account with this common name
```
Sure enough, the certificate is not appearing in my dashboard. I plumbed your help/FAQ and came up broke. Is this a bug?

**Comment by konklone** [comment]
Looks like https://dccode.gov is in fine working order. :)

**Comment by AGWA** [comment]
This was resolved over email way back when.  The problem was that our upstream certificate authority wasn't allowing reissues for the first 30 minutes or so after a cert is issued.  As of today, that should be fixed and reissues should be possible immediately after purchase.
