### ISSUE TITLE
Chef cookbook for sslmate

### ISSUE THREAD

**Issue by konklone** [SSLMate/sslmate#16]
Not requesting - just letting the watchers know that @GUI has put his shovel in the ground on an SSLMate Chef cookbook:

https://github.com/GUI/sslmate-cookbook

As part of potentially automating the certificate issuance and renewal process for api.data.gov. @GUI is also an 18F staff member, using the same account @NoahKunin and I do, so he has DNS access already enabled.

Feel free to close if this is unhelpful, but I figured this also might be a helpful place to identify what, if any, improvements or integrations might be useful between the two repos.

**Comment by AGWA** [comment]
This is totally awesome - thanks for letting me know!  I was planning to start work on tighter configuration management integration later this month, so I am quite interested in discussing this.

**Comment by GUI** [comment]
The cookbook doesn't do much other than automate the install of sslmate from source (which we needed for the DNS-based verification we're testing out), and then adds a couple optional wrappers scripts. Those wrapper scripts aren't particularly elegant, but they do a few basic things to help setup our AWS credentials and automate the installation and management of the sslmate certs into AWS Elastic Load Balancers. (If you're not a Chef person, the wrapper scripts are just some bash shell scripts you can find in the [`cert_*` template files](https://github.com/18F/sslmate-cookbook/tree/master/templates/default)).

If you have thoughts on any of this, or broader configuration management topics, I'd be happy to chat more. But thanks for providing such a wonderfully script-friendly way to get SSL certs! It's certainly a breath of fresh air to be able to automate all this.

**Comment by konklone** [comment]
I'm considering the notification delivered and the introduction made. :)
