### ISSUE TITLE
Error: Invalid certs/ API command using 0.7.0-pre4 with --approval=dns on OSX 10.10.1

### ISSUE THREAD

**Issue by ozzyjohnson** [SSLMate/sslmate#19]
I had no luck buying with DNS approval (I work with @konklone and @GUI using the same DNS-enabled account) from OSX with the following config.

- OSX: 10.10.1
- perl: v5.18.2
- sslmate: 0.7.0-pre4
- boto: 2.37.0
- curl: 7.37.1
- URI: 1.60
- Term::ReadKey: 2.31
- JSON::PP: 2.27202
- WWW::Curl: None

Output:

		sslmate buy --batch --approval=dns DOMAIN
		Generating private key... Done.
		Generating CSR... Done.
		Placing order...
		route53: Adding CNAME record for xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.DOMAIN.... Done.
		Error: Invalid certs/ API command

However, I had no issues attempting the same from a Ubuntu 14.04.1 virtualbox.

- Ubuntu: 14.04.1
- perl: v5.18.2
- sslmate: 0.7.0-pre4
- boto: 2.37.0
- curl: 7.35.0
- URI: 1.60
- Term::ReadKey: 2.31
- JSON::PP: 2.27202
- WWW::Curl: 4.15

Output:

		sslmate buy --batch --approval=dns DOMAIN
		Generating private key... Done.
		Generating CSR... Done.
		Placing order...
		route53: Adding CNAME record for xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.DOMAIN.... Done.
		Order complete.

Happy to provide more information or recreate if I can do so without possibly buying another cert. Keep up the good work.

**Comment by AGWA** [comment]
Thanks for including the version information - it helped me pinpoint the bug very quickly.  I just fixed this in 7bb8da60e215cb6c7a4b634556956dbd71f9e401.
