### ISSUE TITLE
Route 53 error message during failed certificate renewal

### ISSUE THREAD

**Issue by konklone** [SSLMate/sslmate#23]
I got a `route53: Error` amidst my certificate renewal process, which then failed:

```
Press ENTER to confirm order (or q to quit): 
Adding DNS approval record for bit.voyage...
route53: Error: Unrecognized parameter 0
Notice: DNS approval record for bit.voyage was already present.
Placing order...
Error: Activating your certificate failed - please email support@sslmate.com
```

I don't know if the `route53` error was the reason. 

This was with 1.5.0:

```
$ sslmate version
SSLMate 1.5.0
New version of SSLMate available: 1.5.1
```
And I'm having trouble install 1.5.1 for reasons completely unrelated to SSLMate, but as far as I can tell, the changes in 1.5.1 were minimal and unrelated.

**Comment by AGWA** [comment]
Hi @konklone, the activation error was caused by what was apparently a spurious error from our upstream, since your certificate went through anyways and has been issued and delivered.  I'm looking into this in greater detail right now.

As for the route53 error, could you supply your `dns_approval_map` file (with the credentials redacted, of course)?

**Comment by konklone** [comment]
Sure it's:

```
bit.voyage. route53 [redacted] [redacted] [redacted]
```

**Comment by AGWA** [comment]
Ah, looks like you're still using the beta syntax (peril of being a beta tester :-)

It should look like:

```
bit.voyage. route53 aws_access_key_id=[redacted] aws_secret_key_id=[redacted] hosted_zone_id=[redacted]
```

That said, the entire `dns_approval_map` file is optional if suitable credentials are available in `~/.aws/credentials` (which was your very good idea).  That's probably why it was able to proceed in spite of the syntax error.

**Comment by konklone** [comment]
That makes total sense. Thanks for debugging it, and sorry for making you look into something that was not actually a bug!

**Comment by AGWA** [comment]
No worries!  The unrelated activation failed error was definitely a bug, but it will be fixed soon.
