### ISSUE TITLE
letsencrypt question

### ISSUE THREAD

**Issue by peter-mw** [SSLMate/sslmate#24]
can SSLMate be used to manage https://letsencrypt.org/ certificates?

**Comment by MestreLion** [comment]
Not sure, but you surely can do the other way around: use `certbot` to manage SSLMate certificates. `certbot` _defaults_ to Let's Encrypt, but it uses a CA-agnostic ACME protocol that SSLMate supports.

This tutorial explains how to use `certbot` with another CA: https://scotthelme.co.uk/having-a-backup-ca-for-lets-encrypt/
