### ISSUE TITLE
perl error on macOS sierra

### ISSUE THREAD

**Issue by yellottyellott** [SSLMate/sslmate#30]
Installed via `brew` and via the `.pkg`, but I'm getting a perl error when using the cli:

```
$ sslmate --version
Can't locate URI/Escape.pm in @INC (you may need to install the URI::Escape module) (@INC contains: /usr/local/Cellar/perl/5.24.1/lib/perl5/site_perl/5.24.1/darwin-thread-multi-2level /usr/local/Cellar/perl/5.24.1/lib/perl5/site_perl/5.24.1 /usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/darwin-thread-multi-2level /usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1 /usr/local/lib/perl5/site_perl/5.24.1 .) at /usr/local/sslmate/bin/sslmate line 55.
BEGIN failed--compilation aborted at /usr/local/sslmate/bin/sslmate line 55.

$ perl --version

This is perl 5, version 24, subversion 1 (v5.24.1) built for darwin-thread-multi-2level
```

**Comment by yellottyellott** [comment]
Manually installing `URI` and `Term::ReadKey` seems to have fixed it!

```
$ cpan URI
$ cpan Term::ReadKey
$ sslmate version
SSLMate 1.5.1
```

**Comment by bambams** [comment]
If you have cpanm AKA CPAN::minus installed then that's a non-interactive, much less verbose CPAN client.

    $ cpanm URI Term::ReadKey

Just thought that might be useful for some. I know cpan(1) can be a real pain in the butt, especially if you don't use it often.

**Comment by yellottyellott** [comment]
It seems I have perl installed via brew as well, as a dependency of vim. So maybe that local install doesn't have those packages by default while the system one does. `/usr/bin/cpan -l` does list those 2 packages. 

Gonna close this as it may be a nonissue, but it might be worth installing the perl deps as well when doing a `brew install sslmate`.

**Comment by omares** [comment]
I am still running into the issue, albeit i installed the listed packages mentioned by [yellottyellott](https://github.com/SSLMate/sslmate/issues/30#issuecomment-283851382)

cpan says the packages are installed

    cpan -l | grep URI::Escape
    URI::Escape 3.31
    URI::Escape 3.31


    cpan -l | grep Term
    Term::ReadKey   2.37
    Term::ReadKey   2.37
    Pod::Perldoc::ToTerm    3.25
    Pod::Text::Termcap  4.07
    Can't stat /usr/local/lib/perl5/site_perl/5.24.1: No such file or directory
     at /usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/App/Cpan.pm line 1342.
    Term::ANSIColor 4.04
    Term::Cap   1.17
    Term::Complete  1.403
    Term::ReadLine  1.15


    sslmate verison
    Can't locate URI/Escape.pm in @INC (you may need to install the URI::Escape module) (@INC contains: /usr/local/Cellar/sslmate/1.5.1/libexec/vendor/lib/perl5 /usr/local/Cellar/perl/5.24.1/lib/perl5/site_perl/5.24.1/darwin-thread-multi-2level /usr/local/Cellar/perl/5.24.1/lib/perl5/site_perl/5.24.1 /usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/darwin-thread-multi-2level /usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1 /usr/local/lib/perl5/site_perl/5.24.1 .) at /usr/local/Cellar/sslmate/1.5.1/libexec/bin/sslmate line 55.
    BEGIN failed--compilation aborted at /usr/local/Cellar/sslmate/1.5.1/libexec/bin/sslmate line 55.

**Comment by omares** [comment]
Okay, force removing perl installed via homebrew and then reinstalling perl via homebrew and the cpan packages fixed it. I assume some perl paths where broken but i have no clue which exactly.

**Comment by leehinde** [comment]
I'm running MacOS 10.12.6 I'm getting this error; I've uninstalled/reinstalled perl and sslmate to no avail. I'm showing the same installs as @omares but the force uninstall/reinstall dance didn't help.
