### ISSUE TITLE
Support 4096 bit keys with buy & rekey commands

### ISSUE THREAD

**Issue by JonnyPower** [SSLMate/sslmate#32]
Currently, if a user wants to key / rekey with anything other than a key size of 2048 they have to use the rest API to create or update the CSR / Certificate Object manually - which misses out on the convenience factor of using a cli tool to manage your certs.

I know there are downsides to using a 4096 bit key, documented in the FAQ too, but a user should be able to make that choice.

**Comment by AGWA** [comment]
Hi @JonnyPower - you can accomplish this by setting the `rsa_bits` option to `4096` in your config file.

**Comment by JonnyPower** [comment]
Damn, my bad - should have dug further.
