### ISSUE TITLE
Support automated domain approval for new and reissued certificates

### ISSUE THREAD

**Issue by konklone** [SSLMate/sslmate#9]
The `myra.treasury.gov` cert is fine, but I wanted to try reissuing it so I knew that we could replace it any time. I was surprised to find that it needs me to confirm the domain again:

```
$ sslmate reissue myra.treasury.gov

Generating private key... Done.
Generating CSR... Done.
Reissuing cert...
Reissue complete.

You will soon receive an email at admin@myra.treasury.gov from noreply_support@comodo.com. Follow the instructions in the email to verify your ownership of your domain. Once you've verified ownership, your certs will be automatically downloaded.

If you'd rather do this later, you can hit Ctrl+C and your certs will be delivered over email instead.

Waiting for ownership confirmation...
```

Is there no way to make this something that can be done on a cronjob? This is pretty key to getting to a place where we can be throwing away keys every few months or days.

**Comment by konklone** [comment]
Is there any more feedback or assistance we could provide, to be helpful here? Of all the tickets I've filed (and your patience with them has been appreciated!) this is definitely the most game-changing.

**Comment by AGWA** [comment]
Hi @konklone - DNS-based validation is in the works.  It's taking a bit longer than I had planned because I'm revamping the SSLMate API instead of just shoehorning DNS-based validation into the existing API.  Would you/18F be willing to beta test an early version of the client using the new API?

One other thing - I noticed that myra.treasury.gov is using Route 53 - do you plan to use Route 53 for all your domains?  I had actually been considering building Route 53 support into SSLMate...

**Comment by konklone** [comment]
> Would you/18F be willing to beta test an early version of the client using the new API?

Absolutely.

> One other thing - I noticed that myra.treasury.gov is using Route 53 - do you plan to use Route 53 for all your domains? I had actually been considering building Route 53 support into SSLMate...

We do plan to use Route 53 for all 18F's domains, and I'd say that's unlikely to change in the near future.

I don't use it in my personal work, though I'm going to need _some_ kind of API to my personal DNS service if I want to keep fully automated. What will the DNS validation requirements be? Will the TXT record need to change for each validation/reissuance, or can the same one be reused? (In other words, how automate-able must the DNS provider be for the fully automated scenario?)

cc @noahkunin

**Comment by AGWA** [comment]
> > Would you/18F be willing to beta test an early version of the client using the new API?
>
> Absolutely.

Great; thanks!  I'll let you know when it's ready.

> What will the DNS validation requirements be? Will the TXT record need to change for each validation/reissuance, or can the same one be reused?

The DNS record contains the hash of the CSR, so it will have to change whenever the private key changes.  This requirement is essential for security, for pretty much the same reasons I outlined earlier in this issue - the CA has to be sure it's signing the right key.

**Comment by AGWA** [comment]
I'm excited to say that DNS-based approval is up and running, with Route 53 support, in the `apiv2` branch!  It's still very experimental, so it's not officially announced yet, but 18F's account is set up to support it.

To use it, you first need to create a DNS approval map file that maps domains to Route 53 credentials (note the trailing dots on the domains):

```
example.com. route53 AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY HOSTED_ZONE_ID
example.org. route53 AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY HOSTED_ZONE_ID
```

Put the path to the map file in your SSLMate config:

```
dns_approval_map /path/to/mapfile
```

When purchasing a cert, add `--approval=dns` to the `sslmate buy` command line.  Combined with `--batch`, this makes purchases 100% automated.  Reissues will also use DNS approval if the cert was purchased with DNS approval.  Make sure to run `sslmate reissue` from a system that has the approval map configured so that sslmate can update the DNS records.

You need to use an IAM account that has the following permissions:

* `route53:GetChange` on `arn:aws:route53:::change/*`
* `route53:ListResourceRecordSets` on `arn:aws:route53:::hostedzone/HOSTED_ZONE_ID`
* `route53:ChangeResourceRecordSets` on `arn:aws:route53:::hostedzone/HOSTED_ZONE_ID`

For a common name like `www.subdomain.example.com`, SSLMate will create a CNAME record that looks like this:

```
873aca17d7f4ccea19124a69513e6d83.www.subdomain.example.com. CNAME 949602fe304f7ff057aa3fc652f2491c7780f0c1.comodoca.com.
```

`sslmate reissue` removes the old record before adding the new one, so your zone should stay cruft-free.

The system is extensible and designed to support DNS backends besides Route 53 by adding a script to the SSLMate libexec directory.  This will all be documented in due time.

**Comment by AGWA** [comment]
I should add: using Route 53 verification requires Python and [Boto](https://boto.readthedocs.org/en/latest/) (`python-boto` on Debian and Ubuntu).

Also, if you're using Debian or Ubuntu:  I'll be rolling a `.deb` for `0.7.0-pre1` soon and uploading it to an experimental component in the `packages.sslmate.com` APT archive.

**Comment by konklone** [comment]
:clap: :clap: :clap:

I can't wait to try this out, @AGWA! This is super exciting.

**Comment by konklone** [comment]
Could I request access for my personal account (`konklone`) as well?

**Comment by AGWA** [comment]
>  Could I request access for my personal account (konklone) as well?

All set.

**Comment by konklone** [comment]
I successfully bought, and then reissued a cert for https://bit.voyage, and everything worked like a charm. This is fantastic, @AGWA.

I have some interim notes from my work tonight here:
https://gist.github.com/konklone/9ca409139b591a50ba6e

A couple little things:

* The `reissue` command did not remove the old CNAME, so I now have 2 CNAMEs from the buy and reissue. I did run the `buy` and `reissue` commands on two different machines, but the DNS map file was identical, as were the values in the `~/.sslmate` config file.
* `sslmate` is awful persnickety about where the command line flags sit, and it seemed to differ in strictness between `buy` and `reissue`. I think I should be able to run `sslmate buy --approval=dns [domain]` or `sslmate buy [domain] --approval=dns` and have either work, but only the former does.

Some more general feedback is that the setup work involved was quite high, especially compared to the typical `sslmate` experience. My suggestion is to optimize the experience here.

For example, a command could interactively add a line to the DNS map, creating the file if it doesn't exist. (Potentially inside `~/.sslmate`, or in another predictable location.)

How this might work:

```
sslmate domain bit.voyage
```

That literally might be all you need. If `~/.aws/credentials` exists (created by the official AWS CLI when you run `aws configure`, for instance), you could borrow the credentials from there. If it doesn't exist, you could ask for them interactively from the user.

With those credentials, you could also connect to the Route 53 API and list the hosted zones. If a hosted zone's `Name` matches the domain being configured, you could just assume that's the hosted zone, or interactively ask the user to confirm. Worst case, you show the Names and IDs and ask the user to pick which one.

Then when running `sslmate buy [domain]`, if the domain exists in a configured DNS map, assume `--batch` and `--approval=dns`.

It seems like you could hand off the R53-specific pieces of this to callbacks inside the `route53` Python shim, so that other DNS APIs could interact with the user (or not) however they needed to get the DNS map generated.

You could also do this process in-band for the `sslmate buy` command, if someone puts `--approval=dns` and the DNS map hasn't been created or configured for that domain yet.

So for someone who has already installed `boto`, `awscli`, and run `aws configure`, the experience could be:

```
sslmate domain bit.voyage
sslmate buy bit.voyage
```

or just:

```
sslmate buy --approval=dns bit.voyage
```

And it will Just Work, without any editing of a DNS map or `~/.sslmate` required.

**Comment by JoshData** [comment]
This is really great. I'd like to integrate something like this into Mail-in-a-Box (https://mailinabox.email | https://github.com/mail-in-a-box/mailinabox). In Mail-in-a-Box, the box is managing its own self-hosted DNS. Is there a way to invert the control so that Mail-in-a-Box can execute sslmate, sslmate can report what DNS changes need to be made, Mail-in-a-Box can make the changes, and then sslmate can be run again to fetch the certificate? (Mail-in-a-Box has an API that sslmate could call, but that seems too specific.)

**Comment by konklone** [comment]
Not to put words in @AGWA's mouth, but it looks like there's a [hook system](https://github.com/SSLMate/sslmate/tree/apiv2/libexec/sslmate/approval/dns) that's designed to be extensible for other DNS APIs.

The [`route53`](https://github.com/SSLMate/sslmate/blob/apiv2/libexec/sslmate/approval/dns/route53) hook is currently a script with one entry point that does all the work and gets arguments passed in by environment variable. Feels like you could make a `miab` script that talked to the MiaB API too, with the expectation that the DNS map file would need to contain all the credentials needed. (And maybe with MiaB, there aren't any, if it comes from inside the box...?)

**Comment by JoshData** [comment]
That is extremely cool. I could definitely just plop in a hook script.

**Comment by AGWA** [comment]
Thanks @konklone - this is awesome feedback!  I love the idea of looking for credentials  in `~/.aws/credentials` and using `ListHostedZones` to get the hosted zone ID.  I agree it should be possible to substantially reduce the setup work.

> sslmate is awful persnickety about where the command line flags sit

Indeed, there is legacy command line parsing code in some places that is very persnickety.  I'll be fixing this before making an official release.

> The reissue command did not remove the old CNAME, so I now have 2 CNAMEs from the buy and reissue

This should not have happened, even when running `sslmate` on two different systems.  I just tested this again and it worked as expected.  Do you remember if `sslmate reissue` output `route53: Removing CNAME record for...`?  Failure to remove a record is a non-fatal error, so maybe you got incredibly unlucky and there was a transient error right at that moment?  Would you mind trying another reissue, and sending me the output of `sslmate reissue` if the old record isn't removed?

**Comment by AGWA** [comment]
@JoshData - I agree with @konklone that writing a hook would be the way to go.  Don't go coding quite yet, as I will probably be changing the hook API to implement some of @konklone's feedback.  I'll also write up some basic documentation for writing hooks.

SSLMate will also be releasing public API docs so Mail-in-a-Box could bypass the `sslmate` client completely and have total control over the process, but that's probably an unnecessary amount of work.

By the way, Mail-in-a-Box is extremely cool.  I've been hosting my own mail for 10 years now and have always wished more people would do so.  Projects like Mail-in-a-Box can help make that happen.

**Comment by JoshData** [comment]
@AGWA Thanks! An API might be easiest --- I'll be on the lookout for that before I try anything. Keep up the good work!

**Comment by konklone** [comment]
@AGWA I just did another reissue, and it again made another CNAME but did not remove the old one. Here's the output:

```
$ ./bin/sslmate reissue bit.voyage
Generating private key... Done.
Generating CSR... Done.
Reissuing cert...
route53: Adding CNAME record for 1b3679933005da55bdcfebe0bf9e5e2a.bit.voyage.... Done.
Reissue complete.

Waiting for ownership confirmation...

Your certificate is ready for use!

           Private key file: bit.voyage.key
           Certificate file: bit.voyage.crt
     Certificate chain file: bit.voyage.chain.crt
Certificate with chain file: bit.voyage.chained.crt

Tip: generate configuration for this cert with the 'sslmate mkconfig' comman
```

I now have 3 CNAMEs for bit.voyage in Route 53, one for the original issuance, and two for the reissues. I wish I had more helpful debugging information for you -- if there's a `--debug` flag or something, happy to check out new code, re-run the command, and provide more output.

**Comment by AGWA** [comment]
@konklone I found the bug that was preventing CNAME removal.  It was only triggered when the cert was for a bare domain.  It's fixed in the latest push.

**Comment by konklone** [comment]
Just wanted to drop a note in here to say that we used this DNS approval method with 18F's account to create the cert that serves https://https.cio.gov. We used the IAM permissions you laid out to create credentials that could only authorize certificate creation for the `https.cio.gov` hosted zone. 

It was a breeze. :+1:

**Comment by AGWA** [comment]
Totally awesome!   :smile:

And I just pushed some changes to make DNS approval even easier.

First, the DNS approval map now uses named parameters as follows:

    example.org. route53 aws_access_key_id=ID aws_secret_access_key=KEY hosted_zone_id=ID

Every parameter is optional.  If you omit the hosted_zone_id, it will use the domain name to auto-detect the zone ID  (NB: your IAM user needs permission for `route53:ListHostedZones` on `*` for this).  If you omit the credentials, it will read them from `~/.aws/credentials`.

And even the DNS approval map is now optional.  If you have AWS credentials in `~/.aws/credentials`, and a matching domain name in your Route 53 account, then you can just do `sslmate buy --approval=dns example.org` and it will Just Work, with no config required. 

(That said, putting my sysadmin hat on, I would invest the extra time to make my config explicit if integrating this in a deployment process.  For one thing, if something goes wrong, SSLMate can give better error messages if it knows exactly what you want it to do.  But the automatic configuration is great for running SSLMate by hand.)

**Comment by konklone** [comment]
This is really terrific, @AGWA, great job. Do you think a stable release is far off? I'd love to write about it (in my personal capacity for now).

**Comment by konklone** [comment]
Note - I'm not sure if this was the case previously or not, but the use of `ConfigParser` required me to make sure that `python` pointed to Python 2 and not Python 3 (my default).

**Comment by AGWA** [comment]
> Do you think a stable release is far off? I'd love to write about it (in my personal capacity for now).

@konklone - I'm currently aiming for April 15 (which is roughly SSLMate's first birthday).  I have some other announcements planned as well.

>  Note - I'm not sure if this was the case previously or not, but the use of ConfigParser required me to make sure that python pointed to Python 2 and not Python 3 (my default).

Thanks for alerting me to this.  This should be fixed by 2bc1946efdf5d80d333d6cc477dd74e6c8d42663, which once again makes the script agnostic to Python 2 vs Python 3.

**Comment by konklone** [comment]
> @konklone - I'm currently aiming for April 15 (which is roughly SSLMate's first birthday). I have some other announcements planned as well.

Super exciting!

> Thanks for alerting me to this. This should be fixed by 2bc1946, which once again makes the script agnostic to Python 2 vs Python 3.

You could probably set up a little Travis test suite that just imported the library, and have it run in Python 2 and 3, so you'd be notified if this ever regressed. I'll see about a PR for this.

**Comment by AGWA** [comment]
A heads-up to everyone using the apiv2 branch: in the next 12-24 hours I will be pushing a change to the SSLMate backend that will break compatibility with apiv2 clients prior to 8fc69b114df2c557287d4ac8a329c9c235b5a587.  So you should all upgrade as soon as you can to this commit, or newer.  (Normally, I would not break compatibility like this, but since this branch is not officially released yet, it's fair game.)

**Comment by konklone** [comment]
This is now [totally done](https://sslmate.com/help/approval/dns), and is most awesome.
